foreground            #c2c7ce
background            #181c20
selection_foreground  #d4e4f6
selection_background  #394857
url_color             #99ccf9

# black
color0  #505050
color8  #525252

# red
color1  #e57373
color9  #ef9a9a

# green
color2  #81c784
color10 #a5d6a7

# yellow
color3  #f8cf56
color11 #ffe082

# blue
color4  #99ccf9
color12 #9fa8da

# magenta
color5  #c174ce
color13 #ce93d8

# cyan
color6  #4dd0e1
color14 #80deea

# white
color7  #e0e0e0
color15 #fafafa
